menus/urls.py
from django.conf.urls import url

from .views import (
	ItemCreateView,
	ItemListView,
	ItemDetailView,
	ItemUpdateView,
)

urlpatterns = [
    
 	url(r'^create/$',ItemCreateView.as_view(),name='create'),
 	url(r'^(?P<pk>\d+)/$', ItemDetailView.as_view(),name='detail'),
 	url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(),name='edit'),
 	url(r'^$', ItemListView.as_view(),name='list'),
]

myproj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include
from django.contrib import admin
#from restaurants.views import HomeView #AboutView,ContactView #home,contact,about,
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView
from profiles.views import ProfileFollowToggle
from .views import home_page,contact_page,about_page

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page,name='home'),
    url(r'^about/$', about_page,name='about'),
    url(r'^contact/$', contact_page,name='contact'),
    url(r'^$',TemplateView.as_view(template_name='home.html'),name='home'),
    url(r'^login/$', LoginView.as_view(),name='login'),
    url(r'^profile-follow/$',ProfileFollowToggle.as_view(),name='follow'),
    url(r'^u/', include('profiles.urls',namespace='profiles')), #menus=appname
    url(r'^items/', include('menus.urls',namespace='menus')), 
    url(r'^restaurants/', include('restaurants.urls',namespace='restaurants')), #restaurants=appname
#  	url(r'^about/$',TemplateView.as_view(template_name='about_page.html'),name='about'),
#  	url(r'^contact/$',TemplateView.as_view(template_name='contact_page.html'),name='contact'), 	
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/snippets/css.html
{% load static %}

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- 
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
 -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

<link rel='stylesheet' href="{% static 'css/main.css' %}">

<!-- <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
 --> 

templates/snippets/form-snippet.html
{% extends 'base.html' %}
{% block head_title %} {{title}} ||{{block.super}} {% endblock %}	

{% block content %}
<h1>{{title}} </h1>
	{% if form.errors %}
	{{ form.errors }}
	{% endif %}
	<form method='POST' action="">
		{% csrf_token %}
		
		{{form.as_p}}
		<button type='submit'>Submit</button>
	</form><br/>

{% endblock %} 

templates/snippets/js.html
{% load static %}
<!-- jquery cdn-->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

templates/snippets/navbar.html
{% load static %}

	
<nav id="navbar">
	<div class="container">
		<ul>
			<li><a href="{% url 'home' %}">Home</a></li>
			<li><a href="{% url 'contact' %}">Contact</a></li>
			<li><a href="{% url 'about' %}">About</a></li>
			<li><a href="{% url 'restaurants:list' %}">Restaurants</a></li>
			<li><a href="{% url 'menus:list' %}">Menus</a></li>
		</ul>
	</div>
</nav>