menus/urls.py
from django.conf.urls import url

from .views import (
	ItemCreateView,
	ItemListView,
	ItemDetailView,
	ItemUpdateView,
)

urlpatterns = [
    
 	url(r'^create/$',ItemCreateView.as_view(),name='create'),
 	url(r'^(?P<pk>\d+)/$', ItemDetailView.as_view(),name='detail'),
 	url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(),name='edit'),
 	url(r'^$', ItemListView.as_view(),name='list'),
]

myproj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include
from django.contrib import admin
#from restaurants.views import HomeView #AboutView,ContactView #home,contact,about,
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView
from profiles.views import ProfileFollowToggle
from .views import home_page,contact_page,about_page

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page,name='home'),
    url(r'^about/$', about_page,name='about'),
    url(r'^contact/$', contact_page,name='contact'),
    url(r'^$',TemplateView.as_view(template_name='home.html'),name='home'),
    url(r'^login/$', LoginView.as_view(),name='login'),
    url(r'^profile-follow/$',ProfileFollowToggle.as_view(),name='follow'),
    url(r'^u/', include('profiles.urls',namespace='profiles')), #menus=appname
    url(r'^items/', include('menus.urls',namespace='menus')), 
    url(r'^restaurants/', include('restaurants.urls',namespace='restaurants')), #restaurants=appname
#  	url(r'^about/$',TemplateView.as_view(template_name='about_page.html'),name='about'),
#  	url(r'^contact/$',TemplateView.as_view(template_name='contact_page.html'),name='contact'), 	
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends "base.html" %}
{% block head_title %} About||{{block.super}} {% endblock %}	

{% block content %}
	<h1>About Page </h1>
	
	{% include 'snippets/sidebar.html' %}
	
{% endblock %}	

templates/about_page.html
{% extends "base.html" %}

{% block head_title %} About||{{block.super}} {% endblock %}	

{% block content %}
	<div class='row'>
	<div class='col-12 col-md-6'>
	<h2>This is about my business.</h2>

	{% include 'snippets/sidebar.html' %}
	
	</div>
</div>
{% endblock %}	

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block head_title %} lovefood {% endblock %}</title>
	
	{% include 'snippets/css.html' %}
</head>

<body>
{% include 'snippets/navbar.html' %}

<div class="container">
	{% if messages %}
		<div class="alert alert-success messages">
	    {% for message in messages %}
	    <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>
	        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
	        {{ message }}<br/>
	    </span>
	    {% endfor %}
	  	</div>
	{% endif %}
	
	{% block content%}

	{% endblock %}
</div>

{% include 'snippets/js.html' %}


</body>
</html>

templates/contact_page.html
{% extends "base.html" %}

{% block content %}
  <div class='container'>
  <div class='row'>
    <div class='col'>
      <div class='col-md-6 col-12 mx-auto'>
          <form class='contact-form' method='POST' action='{% url "contact" %}'>{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
      </div>
    </div>
  </div>
  </div>

{% endblock %}

templates/form.html
{% extends 'base.html' %}

{% block head_title %} {{title}} ||{{ block.super}} {% endblock %}	

{% block content %}

<h1>{{title}} </h1>
	
	{% if form.errors %}
		{{ form.errors }}
	{% endif %}
	<div class='container'>
  		<div class='row'>
      	<div class='col-md-6 col-12 mx-auto'>
		<form enctype='multipart/form-data' method='POST' action="">
		{% csrf_token %}
		  {{ form.as_p }}
		<button type='submit'>Submit</button>
	</form>
	</div>
</div>
</div>

{% endblock %}

<!-- 
	{% if form.instance %}
		<h1>{{ form.instance.name }}</h1>
	{% endif %} -->
<!-- 
	{% include 'snippets/form-snippet.html' %}
 -->

templates/home_page.html
{% extends "base.html" %}

{% block head_title %} Welcome||{{block.super}} Home {% endblock %}
	
{% block content %}

<div class='container'>
	<div class='col'>
	<div class='jumbotron'>
		<h1 style='color:blue'> Love Food</h1>
		<p> Add your restaurant first, then add menu</p>
		<p><a class='btn btn-default' href='{% url "restaurants:create" %}'> Add restaurant</a>
		<a class='btn btn-primary' href='{% url "menus:create" %}'> Add menu</a></p>
	</div>
	</div>
</div>
{% endblock %}	
<!-- 
<script src='http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js'></script>script>

<script src="js/bootstrap.js"></script>
 -->